Qu-1532/unify logging mechanisms
# Description

Removed the commons-logging dependency from AWS and replaced it with
jcl-over-slf4j

## Type of change

- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing
functionality to not work as expected)
- [ ] Refactor (rebased to a single commit to keep separate from other
changes)
- [ ] This change requires a documentation update

# How Has This Been Tested?

First, after I added the line
```
excludeDependencies ++= Seq(
     ExclusionRule("commons-logging", "commons-logging")
    )
```

I checked the jar and confirmed that org/apache/commons/logging was
removed (which it was)
Then I forced AWS to log by setting the environment variable
`PRINT_LOCATION_ENV_VAR=true` and adding this to main
```  val x = new com.amazonaws.util.VersionInfoUtils()```

After this was added, main threw `java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory` as expected.

Then once I added jcl-over-slf4j, I verified that the error went away.

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have verified my code doesn't add an implementation for something that already exists
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my change is effective and works
- [x] New and existing unit tests pass locally with my changes
- [x] Any changes required of upstream modules have been updated and have explicit tests in this PR
- [x] Any downstream modules depending on this change have an integration plan described in the description

GitOrigin-RevId: 9b8d2cf2d25986db92522e6162525f3889535b62